            - name: Docker build and push
  # You may pin to the exact commit or the version.
  # uses: cloudposse/github-action-docker-build-push@51728c18e98e68a3365054e724b186912d8cbe16
  uses: cloudposse/github-action-docker-build-push@1.16.0
  with:
    # List of extra privileged entitlement (e.g., network.host,security.insecure)
    allow: # optional
    # Set the networking mode for the RUN instructions during build
    network: # optional
    # BuildKit daemon flags
    buildkitd-flags: # optional, default is --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    # List of additional driver-specific options. (eg. image=moby/buildkit:master)
    driver-opts: # optional
    # Working directory
    workdir: # optional, default is ./
    # Dockerfile name
    file: # optional, default is Dockerfile
    # List of build-time variables
    build-args: # optional
    # Organization
    organization: 
    # Repository
    repository: 
    # Docker registry
    registry: 
    # Sets the target stage to build
    target: # optional, default is 
    # List of target platforms for build (e.g. linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,etc)
    platforms: # optional, default is linux/amd64
    # Generate provenance attestation for the build
    provenance: # optional
    # Image name (excluding registry). Defaults to {{$organization/$repository}}.
    image_name: # optional, default is 
    # Docker login
    login: # optional, default is 
    # Docker password
    password: # optional, default is 
    # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
    cache-from: # optional, default is type=gha
    # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
    cache-to: # optional, default is type=gha,mode=max
    # Send the --no-cache flag to the docker build process
    no-cache: # optional, default is false
    # List of SSH agent socket or keys to expose to the build
    ssh: # optional
    # List of tags (supports https://github.com/docker/metadata-action#tags-input)
    tags: # optional
    # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
    secrets: # optional
    # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
    secret-files: # optional
    # Set to `true` to tag images with the PR HEAD SHA instead of the merge commit SHA within pull requests.
    docker-metadata-pr-head-sha: # optional, default is false
    # Enable debug mode
    debug: # optional, default is false
          
